name: flutter_sheet_localization
description: Annotations for the flutter_sheet_localization_generator package.
version: 5.1.2
homepage: https://github.com/aloisdeniel/flutter_sheet_localization
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  intl: ^0.19.0
  template_string:
    git:
      url: https://github.com/NikoBoerger/flutter_sheet_localization.git
      ref: master
      path: template_string
