name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 5.1.7-dep
homepage: https://github.com/aloisdeniel/flutter_sheet_localization
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  meta: ^1.9.1
  csv: ^5.0.2
  recase: ^4.1.0
  code_builder: ^4.4.0
  dart_style: ^2.3.1
  source_gen: ^1.3.2
  flutter_sheet_localization:
    git:
      url: https://github.com/NikoBoerger/flutter_sheet_localization.git
      ref: master
      path: flutter_sheet_localization
  build: ^2.4.0
  analyzer: ^5.12.0
  collection: ^1.17.1
  intl: ^0.18.1
  localization_builder:
    git:
      url: https://github.com/NikoBoerger/flutter_sheet_localization.git
      ref: master
      path: localization_builder

dev_dependencies:
  build_test: ^2.1.7
  build_runner: ^2.4.4
