name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 5.1.7
homepage: https://github.com/aloisdeniel/flutter_sheet_localization
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter 
  http: ^1.2.2
  meta: 1.16.0
  csv: ^6.0.0
  recase: ^4.1.0
  code_builder: ^4.10.1
  dart_style: ^3.1.2
  source_gen: ^3.1.0
  flutter_sheet_localization:
    git:
      url: https://github.com/NikoBoerger/flutter_sheet_localization.git
      ref: master
      path: flutter_sheet_localization
  build: ^3.0.2
  analyzer: ^8.1.1
  collection: ^1.19.0
  intl: ^0.20.2
  localization_builder:
    git:
      url: https://github.com/NikoBoerger/flutter_sheet_localization.git
      ref: 0d54fc8b
      path: localization_builder

dev_dependencies:
  build_test: ^3.3.2
  build_runner: ^2.7.0
