name: localization_builder
description: A data class builder for localization.
homepage: https://github.com/aloisdeniel/flutter_sheet_localization
version: 0.15.8

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter 
  template_string: ^0.6.0
  recase: ^4.1.0
  yaml: ^3.1.2
  equatable: ^2.0.5
  collection: ^1.17.1
  dart_style: ^2.3.1
  logging: ^1.1.1

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.24.2
